failover: false
init_token: CN25LNOPO46HI22UGCNOLT27W8LZJMRAVD3Q9IC4
initialize_email: admin@example.com
initialize_password: password
initialize_username: quayadmin
openshift_api_url: https://api.ocp4.example.com:6443
openshift_password: password
openshift_username: admin
openshift_yaml_dir: /home/ocp/misc_artifacts/quay/quay_only_manifests/
organizations:
  ensono:
    present: true
  proxytest:
    present: true
  test:
    present: false
primary_quay_password: password
primary_quay_user: quayadmin
primary_server: https://central-quay.apps.ocp4.example.com
primary_token: TOOSYDTROY6JEQYLJT2YYV1055KEMEW9RZ1TYRXS
proxycache:
  org1:
    org_name: admin_org
    upstream_registry: quay.io
    upstream_registry_password: password
    upstream_registry_username: user
  org2:
    org_name: proxytest
    upstream_registry: docker.com
quay_admin_org: admin_org
quay_init_config: /home/ocp/misc_artifacts/quay/quay-config-truenas-initial.yaml
repositories:
- org1/hello-podman:v2.0
- org2/hello-podman:latest
- org1/hello-podman1:v1.0
- org3/hello-podman2:v2.0
robot_config:
  bot1:
    name: test
    type: personal
  bot2:
    name: test
    org_name: admin_org
    type: org
secondary_quay_email: admin@example.com
secondary_quay_password: password
secondary_quay_user: quayadmin
secondary_server: https://central-quay.apps.ocp4.example.com
secondary_token: fxb0cpzW52Tskww7Mf2vw0GRwJFYloy8ACz9kJS7\
