failover: false
initialize_email: admin@example.com
initialize_password: password
initialize_username: quayadmin
openshift_api_url: https://api.quay-rep.example.com:6443
openshift_password: password
openshift_username: admin
openshift_yaml_dir: /home/ocp/misc_artifacts/quay/quay_only_manifests/
organizations:
  ensono:
    present: true
  proxytest:
    present: true
  test:
    present: false
primary_init_token: GCM411D4FML0MLRO14A8HHAH6JIPAD6WGQCGCNMB
primary_quay_password: password
primary_quay_user: quayadmin
primary_server: https://central-quay.apps.quay-rep.example.com
primary_token: VIPZTAX30LS5Y98SGU3JB4NM2NAW489IQJ03599T
proxycache:
  org1:
    org_name: admin_org
    upstream_registry: quay.io
    upstream_registry_password: password
    upstream_registry_username: user
  org2:
    org_name: proxytest
    upstream_registry: docker.com
quay_admin_org: admin_org
quay_init_config: /home/ocp/misc_artifacts/quay/quay-config-minio-initial.yaml
repositories:
- ensono/alpine:v1.0
robot_config:
  bot1:
    name: test
    type: personal
  bot2:
    name: test
    org_name: admin_org
    type: org
secondary_init_token: HYSUJWJRLZU9TDYGI22PZHFI5GV7MXMAPTSXBSOS
secondary_quay_email: admin@example.com
secondary_quay_password: password
secondary_quay_user: quayadmin
secondary_server: https://central-quay.apps.ocp4.example.com
secondary_token: X2GJTLY7UDQCU9O3A846MTAHENTFV38MJW8FZSJ1
