DISTRIBUTED_STORAGE_CONFIG:
    default:
        - RadosGWStorage
        - access_key: <key>
          bucket_name: <bucket>
          hostname: <trunas url>
          is_secure: false
          port: 9001
          secret_key: <secret>
          storage_path: <storage path>
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
    - default
DISTRIBUTED_STORAGE_PREFERENCE:
    - default
ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
EXTERNAL_TLS_TERMINATION: true
FEATURE_ANONYMOUS_ACCESS: true
FEATURE_INVITE_ONLY_USER_CREATION: false
FEATURE_REPO_MIRROR: true
FEATURE_USER_INITIALIZE: true
REPO_MIRROR_INTERVAL: 30
REPO_MIRROR_TLS_VERIFY: false
SEARCH_MAX_RESULT_PAGE_COUNT: 10
SEARCH_RESULTS_PER_PAGE: 10
SECURITY_SCANNER_INDEXING_INTERVAL: 30
SERVER_HOSTNAME: <desired quay url>
SETUP_COMPLETE: true
SUPER_USERS:
    - quayadmin
TAG_EXPIRATION_OPTIONS:
    - 2w
TEAM_RESYNC_STALE_TIME: 60m
TESTING: false
BROWSER_API_CALLS_XHR_ONLY: false
FEATURE_PROXY_CACHE: true
